### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by peter-drew**

### CODE REVIEW

**Comment by ZMcWilliam** [comment]
Hey @peter-drew is the issue with students just modifying the team dropdown? If that's the case, is it possible to only disable that and still allow creation and modification of students? It's handy from time to time to be able to modify students, especially if it needs to be done on the day without deleting the team and recreating it

I've put the other changes in #649 so this PR just relates to that now

**Comment by peter-drew** [comment]
It's because if a student is added or deleted through this view the invoice isn't updated. To fix that properly would have added a lot of complexity so I disabled the view and left this only to do CSV exports.

**Comment by evanbailey** [comment]
@peter-drew is there a way that we could trigger invoices/the payments screen to be recached after an alteration is made to students in a team?

I assume this would only be an issue when the event has a per student charge associated with it?

**Comment by peter-drew** [comment]
> @peter-drew is there a way that we could trigger invoices/the payments screen to be recached after an alteration is made to students in a team?
> 
> I assume this would only be an issue when the event has a per student charge associated with it?

I have revisited this and it wasn't as hard as I first feared. Have implemented this as described.

**Pull request merged**
