### PR TITLE
Add withdrawn team field

### PR DESCRIPTION
**Pull request by peter-drew**

### CODE REVIEW

**Comment by peter-drew** [comment]
This is what it looks like in the admin:
image

And on the frontend:
image
image

**Comment by evanbailey** [comment]
This looks great from an interface perspective.

**Comment by peter-drew** [comment]
In that case this is probably ready to go, most of the logic will be on the scoring system side.

**Comment by evanbailey** [comment]
PRs are best merged like voting - early and often 😂

**Pull request merged**
