### PR TITLE
Membership management

### PR DESCRIPTION
**Pull request by peter-drew**
- [x] Add membership model
- [x] Create frontend for setting address and gaining membership
- [x] Create permission level to view membership register

Need to store:
- Phone number (already on user model)
- Birthday - to check if over 18 for ordinary membership
- Address, if and only if over 18
- Date became member (of that type) and date ceased being member (of that type)

To hard code the membership types?

### CODE REVIEW

**Comment by peter-drew** [comment]
@evanbailey the Association management features are now ready for deployment.

This is what it looks like when a user isn't a member:
image

This is what it looks like when they are a member:
image

And if the membership end date is set (users can't do this, only admins):
image

**Comment by peter-drew** [comment]
Address must be set if the member is an ordinary member over 18 years old, otherwise it can't be set.

**Comment by peter-drew** [comment]
Only remaining things to do are confirm all the wording and determine when to deploy this.

**Comment by evanbailey** [comment]
I will need to work out how to get this branch on my local instance so I can play with it before deploying. But I am certainly looking forward to the death of the spreadsheet that is currently used. 

Is there the ability for users to self discontinue their membership, and is there a hsitory log of when people join/self or are admin unjoined?

**Comment by peter-drew** [comment]
At the moment it stores the membership start date and end date (which will be none for an active membership). Once an end date is set the membership is stored in the system but not considered active. It currently isn't possible to then reactivate that membership without losing the record of the previous start/end date. Adding the possibiliy to store an infinite number of previous memberships is possible but I wasn't sure if the complexity is worth it.

At the moment there is no option for people to self discontinue their membership but it isn't hard to add. However because we only store the start and end date of the most recent membership period, if people start creating and deleting memberships frequently this could be an administrative hassle.

**Comment by evanbailey** [comment]
I think what you have done meets the requirements in the Rules of the Association - should be fine & I don't recall having anyone ever leave & return anyway. 
 
 There is another category of memership 'life member' - it would be good to be able to have a checkbox to designate an ordinary member as a life member, and a field to enter the date the committee voted the member as a life member.

**Comment by peter-drew** [comment]
@evanbailey Added the life member field and logic.

**Pull request merged**
