### PR TITLE
Adjust API to show national events in all states

### PR DESCRIPTION
**Pull request by peter-drew**

### CODE REVIEW

**Comment by ZMcWilliam** [comment]
FYI this has caused some unintended side effects 

The calendar @ https://rcja.app/calendar uses the state endpoints to get a list of events _specifically for that state_, so it's now treating events such as nationals or spike prime as many events in many states including NZ

I expect I can fix this by changing how it collates the events and matching based on state IDs then ignoring ones that don't match, so I can have a look into that if we want to keep the API this way
image

The other thing I have noticed is our national events now show up for non-aus states on the website, e.g. NZ - this probably shouldn't be the case if we continue to have NZ as part of the system... 
https://www.robocupjunior.org.au/challenge-regions/nz/nz-events/

---

I assume the intention for this was for the main website to show the NAT events alongside the state events?
Perhaps two alternative solutions:
- Allow the API endpoint to filter to multiple state codes so we can specify `VIC,NAT` for example and it includes both
- OR keep the API how it was and just get the website to do the 2 requests itself on the pages it wants to merge?

@peter-drew thoughts on the best approach?

**Comment by peter-drew** [comment]
@ZMcWilliam maybe if we add an option to endpoints called `includeNational`, which the website can specify on pages where this is desired, but by default not include the national events?

**Comment by ZMcWilliam** [comment]
> @ZMcWilliam maybe if we add an option to endpoints called `includeNational`, which the website can specify on pages where this is desired, but by default not include the national events?

Yeah that works, I think more generally this system is using "global" to describe these sorts of events? `includeGlobal` would be fine, I can easily get the website to add that where needed & it fixes both problems

**Comment by peter-drew** [comment]
I'll implement this in the morning

**Pull request merged**
